/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        'on-primary-container': '#8192a7',
        'on-tertiary-container': '#8292aa',
        'on-secondary-fixed': '#311300',
        'surface-tint': '#4f6073',
        'surface-container-highest': '#e0e3e5',
        'primary-fixed-dim': '#b7c8de',
        'surface-container': '#eceef0',
        'on-tertiary-fixed-variant': '#38485d',
        'primary-container': '#1a2b3c',
        'on-surface': '#191c1e',
        'inverse-primary': '#b7c8de',
        secondary: '#964900',
        'secondary-container': '#fc820c',
        background: '#f7f9fb',
        'on-tertiary-fixed': '#0b1c30',
        'on-background': '#191c1e',
        'tertiary-container': '#1b2b3f',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed': '#d2e4fb',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'on-secondary-container': '#5e2c00',
        'surface-container-high': '#e6e8ea',
        'on-primary-fixed-variant': '#38485a',
        tertiary: '#051629',
        error: '#ba1a1a',
        'tertiary-fixed': '#d3e4fe',
        primary: '#041627',
        'on-primary': '#ffffff',
        'on-secondary-fixed-variant': '#723600',
        'on-tertiary': '#ffffff',
        'outline-variant': '#c4c6cd',
        'tertiary-fixed-dim': '#b7c8e1',
        outline: '#74777d',
        'surface-dim': '#d8dadc',
        'inverse-surface': '#2d3133',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'surface-variant': '#e0e3e5',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#44474c',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#ffb786',
        'secondary-fixed': '#ffdcc6',
        'on-primary-fixed': '#0b1d2d',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'table-data': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'table-data': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
